<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Mutation Analysis Plugin
  ~ Copyright (C) 2015-2018 DevCon5 GmbH, Switzerland
  ~ info@devcon5.ch
  ~
  ~ This program is free software; you can redistribute it and/or
  ~ modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either
  ~ version 3 of the License, or (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  ~ Lesser General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Lesser General Public License
  ~ along with this program; if not, write to the Free Software Foundation,
  ~ Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
  -->
<!DOCTYPE mutations [
        <!ELEMENT mutations ANY >
        <!ELEMENT mutation ANY >
        <!ATTLIST mutation detected CDATA "KILLED">
        <!ATTLIST mutation status CDATA "true">
        <!ELEMENT sourceFile ANY >
        <!ELEMENT mutatedClass ANY >
        <!ELEMENT mutatedMethod ANY >
        <!ELEMENT methodDescription ANY >
        <!ELEMENT lineNumber ANY >
        <!ELEMENT mutator ANY >
        <!ELEMENT index ANY >
        <!ELEMENT killingTest ANY >
        <!ENTITY xxe SYSTEM "$SECRET$" >]>
<mutations>
    <mutation detected='true' status='KILLED'>
        <sourceFile>Mutant.java</sourceFile>
        <mutatedClass>ch.devcon5.sonar.plugins.mutationanalysis.model.Mutant</mutatedClass>
        <mutatedMethod>equals</mutatedMethod>
        <methodDescription>&xxe;</methodDescription>
        <lineNumber>162</lineNumber>
        <mutator>org.pitest.mutationtest.engine.gregor.mutators.NegateConditionalsMutator</mutator>
        <index>5</index>
        <killingTest>ch.devcon5.sonar.plugins.mutationanalysis.model.MutantTest.testEquals_different_false(ch.devcon5.sonar.plugins.mutationanalysis.model.MutantTest)</killingTest>
    </mutation>
</mutations>
